Feat/ratings
DivanteLtd/mage2vuestorefront pull request #107
Opened 2020-11-12 22:17 UTC by soyamore

- Enable the indexation of review ratings

2020-11-16 09:36 UTC, Fifciu requested changes
Good catch. Please add info to the Changelog and I can merge it then

2020-11-17 04:34 UTC, gibkigonzo approved these changes

2020-11-25 19:30 UTC, soyamore commented
@Fifciu Hello Filip change log is added to the PR

2020-11-30 09:25 UTC, Fifciu requested changes

2020-11-30 09:25 UTC, Fifciu commented on CHANGELOG.md
> +## [1.11.12] - 2020-11-12
It is 1.11.2

2020-11-30 13:32 UTC, soyamore commented on CHANGELOG.md
> +## [1.11.2] - 2020-11-12
@Fifciu it's good now,

2020-12-01 11:20 UTC, Fifciu approved these changes

2020-12-01 11:20 UTC, Fifciu commented
Great, thanks!

2020-12-01 11:24 UTC, merged